config/routes.rb
Rails.application.routes.draw do

  get 'users/index'

  get 'admin/index'

  get '/room/:id', to: 'main#room', as: 'main_room'
  get '/category/:id', to: 'main#category', as: 'main_category'

  devise_for :users

  scope "/admin" do
    resources :users
    resources :devices
    resources :room_categories
    resources :categories
    resources :rooms
  end

  root 'main#index'

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  before_action :prepare_sidebar

  def index

  end

  def room
    @room = Room.find(params[:id])
  end

  def category
    @category = Category.find(params[:id])
  end

  private

  def prepare_sidebar
    @rooms = Room.all
    @categories = Category.all
  end


end

app/helpers/main_helper.rb
module MainHelper
  def category_class
    action_name == 'category' ? 'active' : ''
  end

  def room_class
    action_name != 'category' ? 'active' : ''
  end

end

app/views/main/_sidebar.html.erb
<!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">
  <%= content_tag(:li, link_to('Rooms', '#rooms', data: {toggle: 'tab'}), class: room_class)  %>
  <%= content_tag(:li, link_to('Categories', '#categories', data: {toggle: 'tab'}), class:  category_class ) %>
</ul>

<!-- Tab panes -->
<div class="tab-content">

  <%= content_tag(:div, class: "tab-pane " + room_class, id: 'rooms') do -%>
      <% @rooms.each do |room| %>
          <p>	<%= link_to room.name, main_room_path(room)  %> </p>
      <% end %>
  <% end -%>

  <%= content_tag(:div, class: "tab-pane " + category_class, id: 'categories' ) do -%>
      <% @categories.each do |cat| %>
          <p>	<%= link_to cat.name , main_category_path(cat) %> </p>
      <% end %>
  <% end -%>
</div>

app/views/main/category.html.erb
<h2><%= @category.name %></h2>
<% @category.rooms.each do |room|  %>
    <p>
    <h4>
      <%= room.name %>
    </h4>
    </p>
    <% room.room_categories.where(category_id: @category.id).each do |room_cat| %>
        <% room_cat.devices.each do |device| %>
            <%= device.name %>
            <p>
              <%= check_box_tag "switch_#{device.id}", device.on, device.on %>
            </p>
        <% end %>
        <hr>
    <% end %>
<% end %>

app/views/main/index.html.erb
<h1>Main#index</h1>
<p>Find me in app/views/main/index.html.erb</p>

app/views/main/room.html.erb
<h2><%= @room.name %></h2>
<% @room.categories.each do |cat|  %>
    <p><h4><%= cat.name %>
    </h4>
    </p>
    <% cat.room_categories.where(room_id: @room.id).each do |room_cat| %>
        <% room_cat.devices.each do |device| %>
            <%= device.name %>
            <p>
              <%= check_box_tag "switch_#{device.id}", device.on, device.on %>
            </p>
        <% end %>
        <hr>
    <% end %>
<% end %>